linters:
  enable-all: true
  disable:
    - maligned
    - scopelint
    - interfacer
    - golint
    - exhaustruct
    - exhaustive
    - exhaustivestruct
    - dupl
    - nlreturn
    - nonamedreturns
    - varnamelen
    - tagliatelle
    - cyclop
    - gocritic
run:
  timeout: 5m