linters:
  enable-all: true
  disable:
    # deprecated
    - execinquery
    - gomnd
    # unused
    - exhaustruct
    - exhaustive
    - dupl
    - nlreturn
    - tagliatelle
    - cyclop
    - testpackage
run:
  timeout: 3m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  sort-results: true

linters-settings:
  ireturn:
    allow: generic,stdlib,error
  depguard:
    rules:
      main:
        files:
        - $all
        allow:
        - $gostd
        - github.com/Unpackerr/unpackerr
        - github.com/lestrrat-go/apache-logformat
        - github.com/gen2brain/dlgs
        - github.com/getlantern/systray
        - github.com/hako/durafmt
        - github.com/mitchellh/go-homedir
        - github.com/fsnotify/fsnotify
        - github.com/radovskyb/watcher
        - github.com/prometheus/client_golang/
        - github.com/spf13/pflag
        - github.com/julienschmidt/httprouter