linters:
  enable-all: true
  disable:
    # deprecated
    - maligned
    - scopelint
    - interfacer
    - golint
    - exhaustivestruct
    - nosnakecase
    - structcheck
    - deadcode
    - varcheck
    - ifshort
    # unneeded (broken because of generics)
    - rowserrcheck
    - wastedassign
    - sqlclosecheck
    - contextcheck
    # unused
    - exhaustruct
    - exhaustive
    - dupl
    - nlreturn
    - nonamedreturns
    - varnamelen
    - tagliatelle
    - cyclop
run:
  timeout: 3m

