linters:
  enable-all: true
  disable:
    # deprecated
    - execinquery
    - gomnd
    # unused
    - exhaustruct
    - exhaustive
    - dupl
    - nlreturn
    - nonamedreturns
    - varnamelen
    - tagliatelle
    - cyclop
    - tagalign
    - depguard
    - testpackage
run:
  timeout: 3m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0